### ISSUE TITLE
Issues with latest comnit

### ISSUE THREAD

**Issue by DrakeTDL** [bostrot/telegram-support-bot#10]
I just tried out the lastest commit and I found a couple of issues with it. 

The first problem is that I am unable to respond to tickets with a picture attached to them. There was no error an in the console about this. 

The second is that when someone sends a video it says in the this in the console:

>  UnhandledPromiseRejectionWarning:
>  TypeError: Cannot read property '0' of undefined
>     at /mnt/Telegram Bots/TestTelegramSupportBot/bin/ticket_handler.js:164:66
>     at /mnt/Telegram Bots/TestTelegramSupportBot/bin/ticket_handler.js:198:7
>     at /mnt/Telegram Bots/TestTelegramSupportBot/bin/ticket_handler.js:232:7
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> (node:13333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by DrakeTDL** [comment]
Select from gallery

**Comment by DrakeTDL** [comment]
didnt mean to close.

**Comment by bostrot** [comment]
Better late than never:

> I am unable to respond to tickets with a picture

Fixed, see edc1a2cc9ef43920b3b744bdf3d46702304321a4

> sends a video it says

This should have been fixed in 4b61d3b9cef7f18c1863b03438fd928f1e229bf1
