### ISSUE TITLE
Compliation errors : gyp npm

### ISSUE THREAD

**Issue by p1nngu** [bostrot/telegram-support-bot#105]
Hello , im trying to compile the bot  ,but im getting these erros : 

`gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/telegram-support-bot-3.1.1/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 3.10.0-1160.62.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/root/telegram-support-bot-3.1.1/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /root/telegram-support-bot-3.1.1/node_modules/better-sqlite3
gyp ERR! node -v v14.19.3
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.5.3 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-04T12_14_29_999Z-debug.log
`

My OS Version:   CentOS Linux release 7.9.2009 (Core)
My Node Version : v14.19.3

Any solutions?

**Comment by bostrot** [comment]
Seems like some dependencies are not installed. Did you follow the [Getting Started](https://github.com/bostrot/telegram-support-bot/wiki/Getting-started) guide?
