### ISSUE TITLE
Close ticket

### ISSUE THREAD

**Issue by IN80** [bostrot/telegram-support-bot#109]
Hello.

I want to thank you for such a wonderful product. :)

Now the question is: It's not entirely clear what will happen if I disable the automatic closing of a ticket after answering a support message? Will the client be prompted to close the ticket?

**Comment by bostrot** [comment]
Hi,

It means that after the staff replies to a ticket it will close it and that does not notify the user.
This can be good if you use the open tickets (/open) to see what you have replied to already.

**Comment by IN80** [comment]
Now there is an option **auto_close_tickets: false**.

The client writes to the bot, but the ticket is still open. How can the client close it?

**Comment by IN80** [comment]
**/close - close a ticket manually (in case someone writes 'thank you')**

Can such a command be made for clients? If his issue is not resolved in 1 message? And it turns out that in order to solve 1 problem, the client creates a lot of unnecessary tickets.

**Comment by bostrot** [comment]
> Now there is an option **auto_close_tickets: false**.
> 
> The client writes to the bot, but the ticket is still open. How can the client close it?

You can close it with /close



> **/close - close a ticket manually (in case someone writes 'thank you')**
> 
> Can such a command be made for clients? If his issue is not resolved in 1 message? And it turns out that in order to solve 1 problem, the client creates a lot of unnecessary tickets.

I actually started working on something similar some time ago but then stopped because of time. Can you open a new issue as a feature request for that?
