### ISSUE TITLE
Non-latin characters in config.js and response to a message with an attachment

### ISSUE THREAD

**Issue by mie** [bostrot/telegram-support-bot#11]
Hello! Thank you for this project! I use it for our support chat and find very convenient. But still there are things I'd like to see improved. First, I can't use non-latin (cyrillic in my case) characters for greetings and etc. declared in `config.js`. In this case I get no response from the support chat. You've already been [asked](https://discuss.bostrot.com/d/4-bot-not-sending-staff-answer-to-supportee) about this case but there is still no fix.

Secondly, when somebody sends a picture or a video along with the question the reply message to the attachment isn't returned to the bot. This fix would be very helpful.

**Comment by alexandershalin** [comment]
Try not to translated the following string:

lang_from: 'from',

In my case it helped.

**Comment by bostrot** [comment]
Hi, can you try the latest commit and report back whether the not replying thing still not works.
I will soon try to deal with the non-latin characters problem too.

**Comment by alexandershalin** [comment]
I've just checked it and it seems that this issue is not related to Non-Latin characters. Try to change "from" to something different using Latin characters. Result will be the same - user will not receive an answer from support chat.

**Comment by bostrot** [comment]
@alexandershalin well this is a really weird behavior... I just tried adding the non-latin characters you used in your last script which did not work and it works (with: `от` copied from a UTF-8 website. so maybe that is the problem here). To evaluate where this comes from can you send me 1. via telegram @bostrot the used config.js file so I can look into which file format it is and 2. the current keyboard layout you are using.

**Comment by bostrot** [comment]
@mie @alexandershalin 
> I can't use non-latin

> Try to change "from"

That was it. Forgot to change all vars to listen to config/language changes. Thanks.

> Secondly, when somebody sends a picture or a video along with the question the reply message to the attachment isn't returned to the bot.

Fixed, see edc1a2cc9ef43920b3b744bdf3d46702304321a4
