### ISSUE TITLE
launched via npm

### ISSUE THREAD

**Issue by MrKira34** [bostrot/telegram-support-bot#116]
`GrammyError: Call to 'sendMessage' failed! (400: Bad Request: can't parse entities: Character ')' is reserved and must be escaped with the preceding '\')`
When I write a message to the bot, this is the error.

**Comment by bostrot** [comment]
Check if your config.yaml contains this line: `parse_mode: 'MarkdownV2' # DO NOT CHANGE!`.

**Comment by bostrot** [comment]
Seems there is a problem with the new MarkdownV2 escaping. Try to use characters that do not need escaping for now.

**Comment by IN80** [comment]
Did it, nothing changed. The "\" characters also appear at the end of a sentence.

Example: "Thank you for contacting us\. We will answer as soon as possible\."

**Comment by bostrot** [comment]
Try using the latest master branch. This should be fixed.
