### ISSUE TITLE
The client receives only 1 notification that his message has been delivered.

### ISSUE THREAD

**Issue by IN80** [bostrot/telegram-support-bot#121]
Hi!

I mean not to be notified to the user every time his message has been sent. The notification only came when he wrote on the ticket for the 1st time.

**Comment by maslomeister** [comment]
bump, not sure how to fix this

**Comment by bostrot** [comment]
This probably comes from here: https://github.com/bostrot/telegram-support-bot/blob/master/src/users.ts#L163

Try setting the spam time to 0.

**Comment by maslomeister** [comment]
> This probably comes from here: https://github.com/bostrot/telegram-support-bot/blob/master/src/users.ts#L163
> 
> Try setting the spam time to 0.

Thanks!
