### ISSUE TITLE
Error after reply to group member

### ISSUE THREAD

**Issue by alexandershalin** [bostrot/telegram-support-bot#13]
When I reply to another group member in staff_group I got an error:

> An error occured, please report this to your admin: 
> TypeError: Cannot read property '1' of null

Does it affect something and can it be fixed somehow?

**Comment by bostrot** [comment]
Currently this can be ignored. The bot listens to all messages in chat and tries to apply its filter to it. The error handling for this will be done in the next commit

**Comment by bostrot** [comment]
86a7b4ccb5f14ab949f561010c30e0e1846692f2 fixes this.
