### ISSUE TITLE
\ at the end of a sentence

### ISSUE THREAD

**Issue by HabDV** [bostrot/telegram-support-bot#132]
**Describe the bug**
Sorry, I don't know if this is a bug or not.

After command /start
I receive a message like this "Welcome in our support chat\! Ask your question here\."
Slash \ on almost all response messages.
To run I used docker-compose up -d

Ubuntu 20.04
Releases v4.0.1

**Comment by bostrot** [comment]
Can you try the master/main branch instead of the Release version?
Also set parse_mode in your config to "Markdown"
