### ISSUE TITLE
Problem with specific symbol in confg - . ! etc

### ISSUE THREAD

**Issue by s1gne** [bostrot/telegram-support-bot#136]
If i use symbol **.** in config.yaml , example:
language:
  startCommandText: 'Test.'

Telegram send me: Test/.

I think the character **/** appears as a result of escaping symbol **.**

**Comment by bostrot** [comment]
Can you try the master/main branch instead of the Release version?
Also set parse_mode in your config to "Markdown"

**Comment by s1gne** [comment]
> Can you try the master/main branch instead of the Release version? Also set parse_mode in your config to "Markdown"

Oh, sorry , set parse_mode markdown helped me

**Comment by s1gne** [comment]
> Can you try the master/main branch instead of the Release version? Also set parse_mode in your config to "Markdown"

mb u know, why every time, after send message in bot, user get message "undefined" ? thx!

**Comment by bostrot** [comment]
Have you configured it correctly? What is the log output?

**Comment by s1gne** [comment]
> Have you configured it correctly? What is the log output?

Yeah, i take config-example and change only: bottoken,supergroup and owner. 

In files bostrot-error.log , bostrot-output.log, debug.log there is no mention of undefined.
