### ISSUE TITLE
Turn automatic tickets closing off

### ISSUE THREAD

**Issue by alexandershalin** [bostrot/telegram-support-bot#14]
Unfortunately I can't understand from the code, how can I turn automatic tickets closing off. Is there a way to close tickets using "\close" command only?

**Comment by bostrot** [comment]
Currently open tickets are only saved in the bot's cache. When the bot restarts or shuts down they are all discarded. It would need some kind of database to preserve them.

**Comment by alexandershalin** [comment]
Found a workaround. The following string (near line 54) should be commented in ticket_handler.js

//  cache.ticketStatus[userid[1]] = false; // Turn automatic tickets closing off

**Comment by bostrot** [comment]
Done in ef08eea2ae7a7a0e752593459124928d9da1b300. Tickets will now be added to a database and be preserved through its power cycle.
