### ISSUE TITLE
restrict user

### ISSUE THREAD

**Issue by fabston** [bostrot/telegram-support-bot#15]
Are we able to ban/restrict user?

**Comment by bostrot** [comment]
Something like this is not yet implemented in the public version. You can however restrict a user in the code itself by changing some lines:

`ticket_handler.js` (replace line 23, 26):

    if (
      ctx.message.reply_to_message !== undefined &&
      admins.indexOf(ctx.from.id) > -1
    ) {

replace with something like this:

    var bannedUsers = [ // ticket numbers of users to be banned
                                    '907093210', // banned user 1
                                    '422589730', // banned user 2
                                    '521741214' // banned user 3
                                     ];
    if (
      ctx.message.reply_to_message !== undefined &&
      admins.indexOf(ctx.from.id) > -1 &&
      JSON.stringify(bannedUsers).indexOf(ctx.from.id) > -1
    ) {

Where you can define the banned users with their ticket ids. Please report back how this works.

**Comment by fabston** [comment]
Hi there,

Thanks for your reply.

I did update it and replaced it with my test accounts ID however the message keeps being forwarded. I just attached a snipped of my code https://imgur.com/vMYd0Eh.png.

I was also wondering, am I able to use markdown in startCommandText;faqCommandText;lang_contactMessage;lang_blockedSpam?

Thanks again for your help, much appreciated!

**Comment by fabston** [comment]
Oh! I just think we misunderstood each other. In terms of restricting I meant to restrict a user from being able to contact the support / communicate with the bot. So I can ban/restrict spammers lets say.

**Comment by bostrot** [comment]
My mistake, I sent you the wrong section where to implement it. Wrap everything from line 101 to 157 into the statement. See updated reply https://github.com/bostrot/telegram-support-bot/issues/15#issuecomment-481446179

**Comment by fabston** [comment]
No worries, thanks for the update will try that out.

Alright, yes I was using \n already was just hoping to hide links behind text / make text bold. But thats is ok. Looking forward for the update ;)

I was also wondering - the user first name, username (or undefined) can simply be a tag/mention so that I am also able to click on the telegrams profile of a user which did not setup a username. That would prob help a lot.

Anyways, great working bot!

**Comment by bostrot** [comment]
The latest commit ef08eea2ae7a7a0e752593459124928d9da1b300 adds the ability to use the `/ban` option (just like you use `/close`) to restrict users from not being able to write to your staff chat anymore. I also included the way to mention users as you proposed. So there is no username anymore, instead you can click on the users name and see the profile with its id.
Some more minor things are included too. Spam filter is down from 6 messages to 5 per [time you define in config]. Reply how it goes.

**Comment by fabston** [comment]
Ok wow! You implemented everything. Awesome man! Also love the new ticket number option #tID. Sleek! Love it! 

I just tried the `/ban` command by reply. Also getting the` User with ticket #t646148857 banned` however my the user is still being able to use the support bot / messages are being forwarded...

Besides that I am now also facing an issue with systemd which tells me:
```
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
```
Thats def a node issue, already googled it and tried a bunch of commands, so far no luck.

**Comment by bostrot** [comment]
Done e147f48fd675601b93e4146a3c57669ae4505510.

Yes, initially I intended to use the Telegram hashtag system to find older tickets of that user. I didn't expect that a Telegram hashtag has to begin with a normal character and not a number though. Fixed that by putting t in front of it.

You can disable webpage preview by changing l. 192 from: 

    ctx.reply(config.faqCommandText, cache.html);

to

    ctx.reply(config.faqCommandText, Extra.webPreview(false));

I couldn't verify the `lang_contactMessage` popping up more often than before. Should only popup first time a user writes a message and after the staff has replied to a message.

About the `unban` command. Thats a nice idea although I have no plans to implement it right now as you can unban a user by `/close` ing their ticket. I think that should be enough for now.

**Comment by fabston** [comment]
Awesome, it's all working now perfectly. Didnt know that the `/close` would unban a user. Thats totally fine, good to know.

Was prob something on my end then, as `lang_contactMessage` works just fine now.

I was wondering, how do I trigger the `lang_acceptedBy` message? I haven't seen that being used, yet.

**Comment by bostrot** [comment]
The `lang_acceptedBy ` message is triggered by replying `me` to a ticket. This was useful back then when there was no staff chat and staff members wrote directly to the bot. Kind of redundant now.

**Comment by fabston** [comment]
Alright, cool!

**Comment by fbminer** [comment]
Hello again, 

I was wondering if I can turn off webpage preview in `/faq`? A while ago you mentioned to replace `cache.html` with `Extra.webPreview(false)` however after the update that is breaking markdown. Is there any other way to archive that?

I tried to add:
`cache.webPreview = Extra.webPreview(false);` in `support.js` and:
`webPreview: '',` in `cache.js` however that does nothing lol

Thanks for your help!
