### ISSUE TITLE
Docker-compose issue

### ISSUE THREAD

**Issue by Loamanroy** [bostrot/telegram-support-bot#150]
When trying to start the project through docker-compose - docker gives an error Error: ENOENT: no such file or directory, open './config/config.yaml'. What I need to do?
![2023-06-21_16-00-03](https://github.com/bostrot/telegram-support-bot/assets/38310774/0af0333c-1b98-4ca6-8a51-3b4fa51c7d9d)

**Comment by bostrot** [comment]
Exactly what it says: make sure the file config/config.yaml exists and it is actually a file with your config in it.

**Comment by Loamanroy** [comment]
ping @bostrot

**Comment by Tomozki** [comment]
facing the same issue

**Comment by JayDi85** [comment]
It's wrong volumes setup in `docker-compose.yml` — under Windows you must use `%cd%` instead `$(pwd)`.
