### ISSUE TITLE
Bad Request: group chat was upgraded to a supergroup chat

### ISSUE THREAD

**Issue by MothGirlMusic** [bostrot/telegram-support-bot#16]
installed with node.js and npm i, set config, and then ran for the first time. added bot to group and then messaged it... i get this error and nothing goes into the group. it said "supergroup id" in the config.. and with telegram's recent updatings, all groups are supergroups. so what do i do?

```
Ticket:  #t147394605 from Miss Moth Language: de: sdfsdf
(node:13964) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: group chat was upgraded to a supergroup chat
    at buildConfig.then.then.then.then (/var/lib/pufferd/servers/f7ced3dd-1038-4cc4-b1dc-f83ebf60814c/node_modules/telegraf/core/network/client.js:263:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bostrot** [comment]
The bot needs to be an admin in this group and be able to read the messages which can be configured over botfather. Despite the recent update, check out whether you can still convert it into a supergroup like in this picture: 

<img src="https://i.imgur.com/VBnm5az.jpg" height="300"></img>

**Comment by MothGirlMusic** [comment]
i am not able to convert it to a supergroup. the new update added room "permissions" instead of supergroup and normal groups. The bot is admin though, already.

moth@mothnet:~# node -v
v10.15.3
moth@mothnet:~# npm -v
6.9.0

**Comment by bostrot** [comment]
Normally this error comes up when the group ID is changed due to the convertion into a supergroup. As this happens automatically when you give users admin rights (as per the update) you should get the group id again (e.g. with @get_id_bot). The supergroup's ID should start with a `-`. So `-1234567890`.
Try that and please report back.

**Comment by MothGirlMusic** [comment]
you were right! and honestly, I didn't know that at all. thank you though! this fixed the bot and now runs perfectly without error. i feel dumb but then again, i its in a group that no one is the admin of except me because you know, small support staff group doesn't need moderation apart from adding bot as admin so it can read all the messages an such. so i guess i got the ID before adding the bot as admin.

anyway, thank you!
