### ISSUE TITLE
/faq no webPreview

### ISSUE THREAD

**Issue by dducted** [bostrot/telegram-support-bot#20]
Hello again, 

I was wondering if I can turn off webpage preview in `/faq`? A while ago you mentioned to replace `cache.html` with `Extra.webPreview(false)` however after the update that is breaking markdown. Is there any other way to archive that?

I tried to add:
`cache.webPreview = Extra.webPreview(false);` in `support.js` and:
`webPreview: '',` in `cache.js` however that does nothing lol

Thanks for your help!

**Comment by bostrot** [comment]
Just replace 
`ctx.reply(config.faqCommandText, cache.html);` 
at line 184 in bin/support.js with
`ctx.reply(config.faqCommandText, cache.noSound);`
