### ISSUE TITLE
Files are not sent to user

### ISSUE THREAD

**Issue by alexandershalin** [bostrot/telegram-support-bot#21]
**Describe the bug**
Files are not sent to user

**To Reproduce**
1. While replying to user from admin group send him a file as an attachment to your message
2. In admin group it looks like file is sent
3. User doesn't see your message with file attached

**Expected behavior**
User should receive a message with attachment

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Current version of bot script

**Comment by bostrot** [comment]
This behavior is intended. This issue is a feature request and I will try to include file sending support in one of the next releases.

**Comment by bostrot** [comment]
Commit 9d7e4f0b3c62afaf40d472e3d6ad119b6acc9019 adds this features. Cheers!
