### ISSUE TITLE
Tickets don't close properly sometimes

### ISSUE THREAD

**Issue by pilotseye** [bostrot/telegram-support-bot#23]
**Describe the bug**
Some tickets don't close properly when they include the whole tickets text instead of the ID only.
They are shown as closed in the DB, but the /open command shows them as open tickets.

**To Reproduce**
This only happens happens to some tickets, can't figure out what is causing the whole ticket text to end up in the DB instead of the ticket ID only.

**Expected behavior**
Avoid whole ticket text to be put into DB.

**Comment by bostrot** [comment]
Should be fixed with d89297299a165e9b5389dd27fc84ef99d29d7e45. Reopen otherwise.
