### ISSUE TITLE
Tickets did not close

### ISSUE THREAD

**Issue by zavndw** [bostrot/telegram-support-bot#28]
I did not close tickets through the team / close, I found a fork where they recently solved this problem. I tested it
[Fixed tickets /close](https://github.com/dmitry-kotorov/telegram-support-bot/commit/0b58435e9bff766b214265b44546a3de359c5596#diff-40dcec562c40d702ccde9821c8ca4c19)

**Comment by bostrot** [comment]
Duplicate of #23
