### ISSUE TITLE
Whether to support users to create tickets on the web

### ISSUE THREAD

**Issue by wartw** [bostrot/telegram-support-bot#32]
Whether to support users to create tickets on the web

**Comment by bostrot** [comment]
You mean if it is possible to create a ticket on a website/dashboard or just Telegram Web Version? The latter is supported.

**Comment by wartw** [comment]
Create a ticket directly on the personal web page, not a telegram web

**Comment by safly** [comment]
Great work! THX~

**Comment by wartw** [comment]
@bostrot

**Comment by bostrot** [comment]
@wartw

**Comment by wartw** [comment]
> Create

@bostrot

**Comment by wartw** [comment]
Create a ticket directly on the personal web page, not a telegram web

**Comment by bostrot** [comment]
@wartw No.

**Comment by wartw** [comment]
Do not consider adding?  Not everyone uses telegram

**Comment by wartw** [comment]
People who do not use telegram cannot download and use for support

**Comment by wartw** [comment]
@bostrot

**Comment by bostrot** [comment]
@wartw Well, it is a bot for Telegram.

**Comment by wartw** [comment]
https://github.com/idoco/intergram
Can you refer to

**Comment by bostrot** [comment]
@wartw I will look into it and report back.

**Comment by bostrot** [comment]
Would you be willing to help me test this new feature?

**Comment by bostrot** [comment]
Added as an experimental option in master branch.
