### ISSUE TITLE
Sending back images in a reply is producing an error

### ISSUE THREAD

**Issue by MarcBollmann** [bostrot/telegram-support-bot#38]
**Describe the bug**
When replying to a ticket with an image/video/etc. an error occurs

**To Reproduce**
1. Go in the staff chat
2. Click on 'reply' and add an image or gif or video

**Expected behavior**
The user should receive the picture

**Additional context**
undefined
(node:11764) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at C:\Users\mb\Desktop\telegram-support-bot\src\ticket_handler.js:231:14
    at Object.exports.check (C:\Users\mb\Desktop\telegram-support-bot\src\dbhandler.js:13:3)
    at C:\Users\mb\Desktop\telegram-support-bot\src\ticket_handler.js:227:15
    at C:\Users\mb\Desktop\telegram-support-bot\src\ticket_handler.js:293:11
    at C:\Users\mb\Desktop\telegram-support-bot\src\ticket_handler.js:324:7
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by bostrot** [comment]
Does this happen with the releaee version too?

**Comment by MarcBollmann** [comment]
Okay in the release version it's working my fault 👍

**Comment by bostrot** [comment]
> Okay in the release version it's working my fault 👍
> 

Thanks for reporting 👍

**Comment by bostrot** [comment]
Fixed with ec686d51a20c23219be10aef396285759e704f7f in master
