### ISSUE TITLE
Can´t respond to tickets on raspbian lite

### ISSUE THREAD

**Issue by device-null** [bostrot/telegram-support-bot#4]
I´m running this on a rPi3b with a raspbian lite distro (openhabian), node v7.10.1 and npm v5.7.1 installed - had to update npm to the latest version and installed the needed mysql module.

I can run the support.js without problems and receiving user input as a ticket  - via admin-chat and console output. Commands like /start and /faq are also working flawlessly - in the admin-chat as well as in the direct bot-communication.

If I reply (defined as the owner) to one of those tickets, there is no response from the bot - neither in the admin-chat nor to the user directly.

Also I can´t use the /open, /close or /root command. The bot stays silent.... any ideas?

**Comment by bostrot** [comment]
Can you validate that you have set the bot up correctly? Also upload the script (removing personal data) so that I can have a look.

**Comment by bostrot** [comment]
All right. I checked it and it seemed that Telegram has updated it's API since I last used the bot. I just commited an updated version which I can confirm works.
