### ISSUE TITLE
Getting @undefined when user sends an image

### ISSUE THREAD

**Issue by letxbeazero** [bostrot/telegram-support-bot#47]
When the user sends an image through the bot, I get under the image sign like this:
Ticket #T000018 from Eric @undefined Language: en

And when I reply, the user gets a message like this:
Dear Eric @undefined,
text here

**Comment by bostrot** [comment]
Does 7ddebb39d482df51535e91d065aa891425578e10 fix it?

**Comment by letxbeazero** [comment]
> Does [7ddebb3](https://github.com/bostrot/telegram-support-bot/commit/7ddebb39d482df51535e91d065aa891425578e10) fix it?

Yes! Thanks a lot.
