### ISSUE TITLE
Changing some settings values doesn't impact how the bot work

### ISSUE THREAD

**Issue by letxbeazero** [bostrot/telegram-support-bot#48]
It looks like "allow_private" and "direct_reply" in config.ts have no impact on how the bot works. When I change their values to true, or false, the bot works the same way. 
How should it work?

**Comment by bostrot** [comment]
`allow_private` is the setting to allow private chats between a staff member and a user. Only available when using categories. `direct_reply` changes the responding scheme of `allow_private` to forward the user to a direct chat with a staff member. Also only available when allow_private and categories are set.

**Comment by letxbeazero** [comment]
Thank's for your explanation.
