### ISSUE TITLE
newbie question - Cannot access /root interface

### ISSUE THREAD

**Issue by sobelman** [bostrot/telegram-support-bot#5]
Hi,
And thank you for shraring this project, 

When sending /root as admin, the bot / service is entering into some loop and keep sending me message in telegram:
```
Restarted bot. See log
Restarted bot. See log
Restarted bot. See log
Restarted bot. See log
```
While i can see this errors in the logs:
 ```
(node:30598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 400: Bad Request: there is no document in the request
node[30598]: (node:30598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: 400: Bad Request: there is no document in the request

node[30598]: (node:30598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: 400: Bad Request: there is no document in the request

node[30598]: (node:30598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: 400: Bad Request: there is no document in the request

```

I feel like i miss something with /logs/ folder when installing or maybe this is a permission issue, (running on ubuntu) , 
I can't see this folder but i can see in my bin/support.js file that it sholud be exists. 
We be glad for support, 

Thank you. 

> Ubuntu 16.04.3 LTS
> node --version v6.14.0
> npm -v 3.10.10

which node /usr/bin/node
which npm /usr/bin/npm

**Comment by bostrot** [comment]
Yes, normally it tries to save the crash logs from the bot it supports here: `/var/www/html/SUPPORTED_BOT_NAME/logs/log.txt`

So you should look wether you have this directory and create it if it's not there.

Note: The root command is only needed if you want to control another bot with the support bot. Also there is node 8, 9 and 10 out there so you may consider upgrading this (the upgrade wouldn't help getting it work though)

**Comment by sobelman** [comment]
Hi, thanks, Ok, log file is now shown up, (empty) and keep been sending it in a loop, 
Can't see any errors in service console,  (i did not configured any additional bot to control) But i wonder why i can't get the following message in replay: 
https://camo.githubusercontent.com/1bab96a8c1f14a9f089f4a325ad67dbda09a4f84/68747470733a2f2f7075752e73682f77797765352f613463336365653062372e706e67

Thanks

**Comment by sobelman** [comment]
thank you.
