### ISSUE TITLE
Cant pull docker image

### ISSUE THREAD

**Issue by Foresto-rip** [bostrot/telegram-support-bot#50]
Hello!
I'm trying start bot by docker-compose but your image is private:
```
[root@node1 telegram-support-bot]# docker-compose up -d
Pulling supportbot (bostrot/telegram-support-bot:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling supportbot (bostrot/telegram-support-bot:latest)...
ERROR: pull access denied for bostrot/telegram-support-bot, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Best regards, Sergey.

**Comment by bostrot** [comment]
Oh yes, I removed it a while ago because it had a configuration error and I had no time to fix it. I will upload a new image shortly. Thank you for reminding me.

Until then you can build it on your own with:

    docker build -t bostrot/telegram-support-bot:latest .

And then run with your docker-compose file or something like this:

    docker run bostrot/telegram-support-bot -v /path/to/config_dir:/bot/config

**Comment by bostrot** [comment]
I just re-uploaded the latest build of this to the docker registry.
