### ISSUE TITLE
Messages are lost on Exception

### ISSUE THREAD

**Issue by 2naive** [bostrot/telegram-support-bot#52]
**Describe the bug**
If any error happens on sending message from/to user -> message just got lost and moderator/users receives reply that everything is fine https://github.com/bostrot/telegram-support-bot/blob/master/src/text.ts#L19

**To Reproduce**
1. Send **<** to bot
2. You will get _Thank you for contacting us. We will answer as soon as possible._
3. No message would be sent to support group due to error
4. Send **1** to bot
5. Reply to **1** with **<** from support group
6. You will get _Message sent to user Alexander_ but no message would be sent due to error

**Expected behavior**
1. If **ANY** error happens -> catch it, reply with "Error happend" to sender, notify support group about an error.
2. Special chars should be escaped

```
greensms_bot    | === UNHANDLED REJECTION ===
greensms_bot    | "Fri Apr 23 2021 00:31:56 GMT+0000 (Coordinated Universal Time): Error: 400: Bad Request: can't parse entities: Unclosed start tag at byte offset 60\n" +
greensms_bot    |   '    at /bot/node_modules/telegraf/core/network/client.js:281:17\n' +
greensms_bot    |   '    at processTicksAndRejections (node:internal/process/task_queues:94:5)'
```

**Comment by 2naive** [comment]
I've lost so many messages from/to my clients this year because of this :(

**Comment by 2naive** [comment]
And bot.catch() https://github.com/bostrot/telegram-support-bot/blob/master/src/index.ts#L91
is not working due to: https://github.com/telegraf/telegraf/issues/491
or could be solved just with
```
bot.catch((err, ctx) => {
  console.log('Error: ', err)
  ctx.reply('Message is not sent due to an error')
});

**Comment by bostrot** [comment]
The code you posted doesn't work with unhandled rejections. 
For now I escaped some HTML characters as a quick fix and made the error handler send a message to the staffchat in case anything happens.

See 9f44bd6d19272a8bb0bc5aae08d507e5c1526c22.
