### ISSUE TITLE
autoreply on keywords

### ISSUE THREAD

**Issue by noxonsu** [bostrot/telegram-support-bot#59]
our clients send us many duplicated questions, for example, they want to hire us for a custom job, would be perfect if the bot automatically replies to these messages using a template. 

for example:
client: Hello, are you available for a **custom development**?
bot: Sorry, but we not doing custom development. Only fixing bugs and helps with problems. Thanks

**Comment by bostrot** [comment]
I thought about that too a while ago. This would probably be very useful.
Will keep that in mind for the next update.

**Comment by bostrot** [comment]
I implemented an experimental version of this with commit ff4e7aa.

User side:
![image](https://user-images.githubusercontent.com/7342321/126774016-6d8207af-142f-4e32-ab5f-b5a6c49b37fb.png)

Staff side:
![image](https://user-images.githubusercontent.com/7342321/126773975-4bf5b598-5768-41e9-a011-82ad6396e87f.png)

where keywords are defined in `config/strings.ts`:

```
const strings = [
    [ "how do I install this?", "You don't." ],
    [ "are you sure?", "Yes." ],
    [ "Some other Case Sensitive Text", "OK." ],
]
```
