### ISSUE TITLE
Bad Request: can't parse entities

### ISSUE THREAD

**Issue by kultpro** [bostrot/telegram-support-bot#67]
I'm sorry that I'm providing information out of form. In addition, I am still using the version from 11 Jul.

1. It seems that the problem is an unclosed tag in the name

`Fri Sep 03 2021 19:17:25 GMT+0000 (Coordinated Universal Time): consultation #T000386 для <a href=""><3</a>  : ru`

A message has been received from the user, but it is impossible to respond to it

`An error occured, please report this to your admin: 
 Error: 400: Bad Request: can't parse entities: Unsupported start tag "3</a" at byte offset 52`

2. The message from the user did not reach the chat, but I see it in the log. I think that the problem is in the long dash in the name

```
Sat Sep 04 2021 21:12:05 GMT+0000 (Coordinated Universal Time): SqliteError: near "for": syntax error
    at Object.getOpen (/telegram-support-bot/src/db.ts:23:23)
    at Object.chat (/telegram-support-bot/src/staff.ts:91:8)
    at ticketHandler (/telegram-support-bot/src/text.ts:47:11)
    at Object.handleText (/telegram-support-bot/src/text.ts:28:5)
    at /telegram-support-bot/src/index.ts:89:33
    at /telegram-support-bot/node_modules/telegraf/composer.js:143:56
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
    
```
    An error occured, please 
          report this to your admin:
SqliteError: near "for": syntax error
```

**Comment by bostrot** [comment]
Probably similar behavior to #52. Escaping characters in the name might help.

**Comment by bostrot** [comment]
Commit c27d619d82132b2b92a1b185c7249baa43317646

Should fix that behavior by escaping the user's names.

This will be in the release of version 3.0.0.
