### ISSUE TITLE
Error: 403: Forbidden: bot was kicked from the supergroup chat

### ISSUE THREAD

**Issue by bostrot** [bostrot/telegram-support-bot#71]
**Describe the bug**
Simliar to #65 unhandled rejections occur when the bot was kicked from a supergroup while trying to reply to a message.

**Additional context**

    === UNHANDLED REJECTION ===
    'Thu Sep 16 2021 12:42:54 GMT+0200 (Central European Summer Time): Error: 403: Forbidden: bot was kicked from the supergroup chat\n' +
      '    at /home/bostrot/proj/telegram-support-bot/node_modules/telegraf/core/network/client.js:281:17\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)'

**Comment by bostrot** [comment]
Commit af43951c5ff80831b9ce2681b7d7e6b35417a8f4 should improve error handling with catching the reply function.
Still needs to be tested if it actually solves it as the error is hard to reproduce.

**Comment by bostrot** [comment]
Closing for now as that commit should have fixed it for now. Reopen if that error reoccurs.

**Comment by chakzefir** [comment]
Hey @bostrot 
I'm getting an error adding bot to supergroup, are there any workaround to fix it?

```
Thu Jun 23 2022 06:31:19 GMT+0000 (Coordinated Universal Time): Error: 400: Bad Request: group chat was upgraded to a supergroup chat
```

**Comment by bostrot** [comment]
> Hey @bostrot 
> I'm getting an error adding bot to supergroup, are there any workaround to fix it?
> 
> ```
> Thu Jun 23 2022 06:31:19 GMT+0000 (Coordinated Universal Time): Error: 400: Bad Request: group chat was upgraded to a supergroup chat
> ```

Yes, see following: https://github.com/bostrot/telegram-support-bot/issues/16#issuecomment-491625213

**Comment by chakzefir** [comment]
@bostrot thank you.
Updated settings in bot father (for the **group**), also gave it admin privileges in group (even they are not required). 
![bot](https://user-images.githubusercontent.com/5852099/179491490-9b4f1017-a11b-4c1b-ac46-d55c122ac1c6.png)

Bot continues to reply: `Message is not sent due to an error.`

And the logs like this:
```
'Mon Jul 18 2022 10:05:20 GMT+0000 (Coordinated Universal Time): Error: 400: Bad Request: chat not found\n' +
```

p.s. Working fine while not in supergroup.

**Comment by bostrot** [comment]
> @bostrot thank you.
> Updated settings in bot father (for the **group**), also gave it admin privileges in group (even they are not required). 
> ![bot](https://user-images.githubusercontent.com/5852099/179491490-9b4f1017-a11b-4c1b-ac46-d55c122ac1c6.png)
> 
> Bot continues to reply: `Message is not sent due to an error.`
> 
> And the logs like this:
> ```
> 'Mon Jul 18 2022 10:05:20 GMT+0000 (Coordinated Universal Time): Error: 400: Bad Request: chat not found\n' +
> ```
> 
> p.s. Working fine while not in supergroup.

Please recheck your Group ID with the /id command.
