### ISSUE TITLE
Errors when executing "npm run prod"

### ISSUE THREAD

**Issue by rccardero** [bostrot/telegram-support-bot#74]
**Describe the bug**
After executing "npm run prod" the process fails with the errors shown in the screenshot.

**To Reproduce**
git clone https://github.com/bostrot/telegram-support-bot.git
cd telegram-support-bot
npm i
mv config/config-sample.yaml config.yaml
I configure the file config.yaml, and,
npm run prod

**Expected behavior**
The process ran without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/38739177/136143598-0a9a4cb1-1545-4304-a5aa-964ce44b139e.png)

**Additional context**
Debian GNU/Linux 10 (buster)

**Comment by bostrot** [comment]
Try running release [v2.0.2](https://github.com/bostrot/telegram-support-bot/releases/tag/v2.0.2) the master branch is not stable yet. 

Also with the master branch it indicates that the directory /build/src/addons/web does not exist. Start with creating that.

**Comment by bostrot** [comment]
Are you sure you are running the docker image with the right version? (e.g. `bostrot/telegram-support-bot:2.0.2` if docker-compose image tag says `latest` change that to `2.0.2`).

(btw `docker-compose log` gives you a cleaner log than tail)
