### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kultpro** [bostrot/telegram-support-bot#76]
Thank you very much for all the new updates! There are small errors.

1. When the user clicks "Start" and receives the contents of "start Command Text" of any content and language, an error arrives to the admin:

```
An error occured, please report this to your admin:
TypeError: Cannot read property 'length' of undefined
```

**Comment by kultpro** [comment]
node --version
v14.18.1

**Comment by bostrot** [comment]
Thanks for reporting. I have noticed those messages too but haven't had any time to look into it yet. Good to know where that comes from.

I guess this happens with the v3.x.x of the bot (master branch)?
(There is no stable release for that version yet. Latest stable is v2.0.2)

**Comment by kultpro** [comment]
> I guess this happens with the v3.x.x of the bot (master branch)? (There is no stable release for that version yet. Latest stable is v2.0.2)

Yes, "telegram-support-bot@3.0.0"

**Comment by kultpro** [comment]
```
=== UNHANDLED REJECTION ===
TypeError: Cannot read property 'length' of undefined\n" +
at /telegram-support-bot/src/index.ts:73:33\n' +
at /telegram-support-bot/node_modules/telegraf/composer.js:143:56\n' +
at processTicksAndRejections (internal/process/task_queues.js:95:5)'
```

**Comment by kultpro** [comment]
This can be used to understand how many users have used the bot, but have not created a consultation :)

**Comment by bostrot** [comment]
Commit dc5e207 should fix this.

**Comment by kultpro** [comment]
This problem is no longer there. Thanks!
