### ISSUE TITLE
Info on author of a message forwarded to the bot

### ISSUE THREAD

**Issue by designbydj** [bostrot/telegram-support-bot#80]
**Is your feature request related to a problem? Please describe.**

When a user forwards a message I get the content of it, but no information about the author of the forwarded message

**Describe the solution you'd like**
If it's a forwarded message please add the meta information of the author (link to profile, name and user id)

*Alternative*
Forward the forwarded message to the staff group as a forwarded message 

**Additional context**
Some user use the support to report message of others by forwarding the violating message to an admin. But currently we don't see that information.

**Comment by Venipa** [comment]
the feature is to anonymize users
![image](https://user-images.githubusercontent.com/17952364/173129488-2ddeb909-e933-457c-b0b9-695e68730894.png)
