### ISSUE TITLE
@bostrot_bot is broken (dont have answer), use @RawDataBot

### ISSUE THREAD

**Issue by evdevru** [bostrot/telegram-support-bot#83]
Your bot [@bostrot_bot](https://t.me/bostrot_bot) have big delay or broken.
I will add him and get answer only after 2 hours.
Instead of him i use [@RawDataBot](https://t.me/RawDataBot) and get instant answer with params "message.chat"
I lost your bot answer, but have bot commands:
![alt text](https://i.imgur.com/dz41EC2.png)

**Comment by bostrot** [comment]
As you can read the message 

"Dev mode is on: You might notice some delay in messages, no replies or other errors."

the bot was offline during that time and  is still being developed on.
