### ISSUE TITLE
Error when close ticket

### ISSUE THREAD

**Issue by L4R4** [bostrot/telegram-support-bot#86]
**Describe the bug**
When i use command /close for close a ticket, this messaje is showing: 

TypeError: Cannot read properties of null (reading '1')

I asumme that hapennig when tried to close an already closed ticket But i not sure about

**Comment by bostrot** [comment]
I cannot reproduce this. Please post some details on what you did to receive this error.

**Comment by mte0** [comment]
@bostrot
