### ISSUE TITLE
Move text strings to a separate file

### ISSUE THREAD

**Issue by alexandershalin** [bostrot/telegram-support-bot#9]
Moving text strings to a file ("Dear ", "FAQ: " etc.) would be very helpful for localization to other languages.

**Comment by bostrot** [comment]
Heads up, I just pushed a commit (e4ddd84f7a04d40226209602c3a09bfcfab66616) which also includes this. All strings are now located in `config.js`.

![strings](https://i.imgur.com/DmtOziz.png)

**Comment by alexandershalin** [comment]
Thank you so much! Trying to set up new version of bot rught now :)
