### ISSUE TITLE
Messages are received in staff chat, but replies do not go to user! Commands don't work either!

### ISSUE THREAD

**Issue by XMVZ** [bostrot/telegram-support-bot#96]
**Describe the bug**
Everything is set up properly on Debian. 
I have tried with GROUP and SUPERGROUP.
The bot is admin.
The console is not throwing any errors...

![image](https://user-images.githubusercontent.com/79497004/174516758-cc61898e-8818-48ce-bc0e-0dcd311b79a4.png)

**To Reproduce**
1. Send a message to the bot.
2. Message is received in chat.
3. Reply to message does not go to user.
4. Commands don't work either.

**Expected behavior**
Commands and messaging working...

**Screenshots**
EVERYTHING IS SET UP PROPERLY!

![image](https://user-images.githubusercontent.com/79497004/174516916-5b29b0f2-eb6f-4e02-8bf5-6e0aa7607ec9.png)
![image](https://user-images.githubusercontent.com/79497004/174516952-2f1b4433-a925-45cd-b64d-c849ffa212ab.png)

**Additional context**
Dev mode is also OFF but it says it's on...

What do I do?

**Comment by XMVZ** [comment]
Something new...

![image](https://user-images.githubusercontent.com/79497004/174537616-f5acc0e0-83ac-4141-9141-541e937b878c.png)
![image](https://user-images.githubusercontent.com/79497004/174537727-2aaa2b60-0133-4092-bf63-5c7af6004a06.png)

**Comment by XMVZ** [comment]
![image](https://user-images.githubusercontent.com/79497004/174537767-e1d697b2-30eb-4209-8ea3-daf824011359.png)

**Comment by bostrot** [comment]
Two bots are answering because you have the Bostrot Support Bot in your
group too. You should remove that. Also make sure that everyone in your
group that is replying has admin privileges in that group. You can also
check the config/debug.log for more logs.

XMVZ ***@***.***> schrieb am Mo., 20. Juni 2022, 08:22:
